# Generated by Django 4.1.7 on 2023-06-22 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LRN', models.PositiveIntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('suffix_name', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('religion', models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('roman catholic', 'Roman Catholic'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('sikhism', 'Sikhism'), ('other', 'Other')], default='other', max_length=30, null=True)),
                ('other_religion', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, choices=[(1, 'Yearly'), (2, '1st Semester'), (3, '2nd Semester')], null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=120, null=True)),
                ('father_contact', models.IntegerField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mother_contact', models.IntegerField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=120, null=True)),
                ('guardian_contact', models.IntegerField(blank=True, null=True)),
                ('last_grade_level', models.IntegerField(blank=True, null=True)),
                ('last_school_attended', models.CharField(blank=True, max_length=30, null=True)),
                ('last_schoolyear_completed', models.CharField(blank=True, max_length=4, null=True)),
                ('school_id_number', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, choices=[('A', 'STEM'), ('B', 'BAM'), ('C', 'HESS'), ('D', 'SPORTS & ARTS'), ('E', 'TVL'), ('N/A', 'Not Applicable')], max_length=15, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('economic_range', models.CharField(blank=True, choices=[('A', 'Upper Class: above Php 35,000'), ('B', 'Middle Class: from Php 18,000 - Php 35,000'), ('C', 'Working Class: from Php 9000 - Php 18,000'), ('D', 'Lower Class: below Php 9000')], max_length=1, null=True)),
                ('is_returnee', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=1, null=True)),
                ('is_a_dropout', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=1, null=True)),
                ('is_a_working_student', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=1, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_adviser', models.CharField(blank=True, max_length=50, null=True)),
                ('adviser_contact', models.IntegerField(blank=True, null=True)),
                ('health_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_a_four_ps_scholar', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=1, null=True)),
                ('classroom', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.classroom', verbose_name='Classrooms')),
                ('gradelevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.gradelevel')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalStudent',
        ),
    ]
