# Generated by Django 4.1.7 on 2023-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_studentrecord_delete_historicalstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
