# Generated by Django 4.1.7 on 2023-06-25 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_remove_student_last_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('LRN', models.PositiveIntegerField()),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('suffix_name', models.CharField(blank=True, max_length=10)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('religion', models.CharField(choices=[('christianity', 'Christianity'), ('roman catholic', 'Roman Catholic'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('sikhism', 'Sikhism'), ('other', 'Other')], default='other', max_length=30)),
                ('other_religion', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField()),
                ('sem', models.IntegerField(choices=[(1, 'Yearly'), (2, '1st Semester'), (3, '2nd Semester')], null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('birth_place', models.CharField(max_length=20)),
                ('mother_tongue', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=120)),
                ('father_contact', models.IntegerField()),
                ('mother_name', models.CharField(max_length=120)),
                ('mother_contact', models.IntegerField()),
                ('guardian_name', models.CharField(max_length=120)),
                ('guardian_contact', models.IntegerField()),
                ('last_grade_level', models.IntegerField()),
                ('last_school_attended', models.CharField(max_length=30)),
                ('last_schoolyear_completed', models.CharField(max_length=4)),
                ('school_id_number', models.IntegerField()),
                ('strand', models.CharField(choices=[('A', 'STEM'), ('B', 'BAM'), ('C', 'HESS'), ('D', 'SPORTS & ARTS'), ('E', 'TVL'), ('N/A', 'Not Applicable')], max_length=15)),
                ('text', models.TextField(blank=True, null=True)),
                ('economic_range', models.CharField(choices=[('A', 'Upper Class: above Php 35,000'), ('B', 'Middle Class: from Php 18,000 - Php 35,000'), ('C', 'Working Class: from Php 9000 - Php 18,000'), ('D', 'Lower Class: below Php 9000')], max_length=1)),
                ('is_returnee', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_a_dropout', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_a_working_student', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('previous_school', models.CharField(max_length=50)),
                ('previous_adviser', models.CharField(max_length=50)),
                ('adviser_contact', models.IntegerField()),
                ('health_bmi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_a_four_ps_scholar', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classroom', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.classroom', verbose_name='Classrooms')),
                ('gradelevel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.gradelevel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student',
                'verbose_name_plural': 'historical Students',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
