# Generated by Django 4.1.7 on 2023-06-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_historicalteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRecord',
        ),
    ]
