# Generated by Django 4.1.7 on 2023-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_historicalstudent_school_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
